import { Darker_Grotesque, Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import Footer1 from "@/components/footer1";
import Header1 from "@/components/header1";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable : "--font-inter",
  subsets : ["latin"]
})
const poppins = Poppins({
  variable : "--font-primary",
  subsets : ["latin"],
  weight : ['100','200','300','400','500','600','700']
})


const grotesque = Darker_Grotesque({
  variable : "--font-secondary",
  subsets : ["latin"],
  weight:['300','400','500']
})

const myFont = localFont({
  src: [
    { path: '../../public/fonts/GlacialIndifference-Regular.otf', weight: '400', style: 'normal' }, 
  ],
  
  variable: '--font-myfont', // optional CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} ${poppins.variable} ${myFont.variable} font-primary antialiased relative w-full h-max scroll-smooth`}
      >
        <Header1/>
        {children}
        <Footer1/>
      </body>
    </html>
  );
}
